
ADD_SUBDIRECTORY(SIX_NFW_SPRE)
ADD_SUBDIRECTORY(SHAKTI_C)
ADD_SUBDIRECTORY(ROCKET)
ADD_SUBDIRECTORY(CV32E40P_CORE)
ADD_SUBDIRECTORY(CVA6)
ADD_SUBDIRECTORY(AssemblyTrace)
ADD_SUBDIRECTORY(CVA6_QWEN_1)
ADD_SUBDIRECTORY(LAMP)
ADD_SUBDIRECTORY(FOUR_NFW_NOPRE)
ADD_SUBDIRECTORY(CV32E40P_LLM)
ADD_SUBDIRECTORY(FIVE_NFW_NPRE)
ADD_SUBDIRECTORY(FIVE_FW_DYPRE)
ADD_SUBDIRECTORY(CV32E40P_QWEN_1)
ADD_SUBDIRECTORY(CVA62)
ADD_SUBDIRECTORY(InstructionTrace_RV64)
ADD_SUBDIRECTORY(CV32E40P)

